### ISSUE TITLE
Make the footer configurable from the sysadmin config page

### ISSUE THREAD

**Issue by JasminaPN** [keitaroinc/ckanext-kepa#28]
**To Do:**

Make the footer part of the KEPA metadata portal configurable through the sysadmin config page.

Current behavior: the links are hard-coded in the HTML templates 

An example of this is data.gov.mk

**Comment by gocemitevski** [comment]
Best if we can re-implement these lists in similar fashion to https://github.com/keitaroinc/ckanext-datagovmk/blob/master/ckanext/datagovmk/templates/snippets/footer_links.html. That way the Customer can manage these information without our involvement.

**Comment by Magi-Jakimovska** [comment]
@ivangorkov, this requirement is out of scope; please discuss it with the client first as an opportunity for improvement and a possible upsell.
Estimates from the team were provided on the call today, and are as follows:
BE: 4-8h
FE: 4-8h

cc: @JasminaPN, @gocemitevski, @blagojabozinovski, @jovanak98

**Comment by jovanak98** [comment]
Thank you @gocemitevski no further support needed so far, i did sync with Blagoja and this will be done as it should be correctly

**Comment by blagojabozinovski** [comment]
On the web interface in /ckan-admin/config settings there is a possibility to add the custom links that will appear in the footer sections.

**Comment by gocemitevski** [comment]
@blagojabozinovski feel free to mention the relevant PRs or issues within their title or description, so they get connected automatically. https://github.com/keitaroinc/ckanext-kepa/pull/30

@Magi-Jakimovska it is crucially important to have a comment that refers to the relevant code change before closing an issue and marking it as done.
